apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: grafana
type: Opaque
stringData:
  client_id: "REPLACE_WITH_AUTHENTIK_CLIENT_ID"
  client_secret: "REPLACE_WITH_AUTHENTIK_CLIENT_SECRET"
