apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/sources.yaml
  - infrastructure/cert-manager.yaml
  - infrastructure/dapr.yaml
  - infrastructure/traefik.yaml
