apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - traefik.yaml
  - goauthentik.yaml
  - grafana.yaml
  - grafana-community.yaml
  - prometheus-community.yaml
