---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: dapr-system
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "tempo.tempo.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc
  metric:
    enabled: true
