---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-dev-spoletum-tls
  namespace: traefik
spec:
  secretName: wildcard-dev-spoletum-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.dev.spoletum.net"
    - dev.spoletum.net
