apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - cert-manager.yaml
  - traefik.yaml
  - authentik.yaml
  - tempo.yaml
  - prometheus.yaml
  - loki.yaml
  - alloy.yaml
  - grafana.yaml
