apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-traefik
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/components/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-sources
    - name: infrastructure-cert-manager
  patches:
    - target:
        kind: HelmRelease
        name: traefik
      patch: |-
        - op: replace
          path: /spec/values/service/annotations/load-balancer.hetzner.cloud~1name
          value: dev
        - op: add
          path: /spec/values/gatewayAPI
          value:
            enabled: true
        - op: add
          path: /spec/values/gateway
          value:
            enabled: true
            name: traefik-gateway
            listeners:
              web:
                port: 8000
                protocol: HTTP
              websecure:
                port: 8443
                protocol: HTTPS
                allowedRoutes:
                  namespaces:
                    from: All
