apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: nelcaso
  labels:
    app.kubernetes.io/name: nelcaso-core
    app.kubernetes.io/instance: nelcaso-core
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nelcaso-core
      app.kubernetes.io/instance: nelcaso-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nelcaso-core
        app.kubernetes.io/instance: nelcaso-core
      annotations:
        dapr.io/app-id: nelcaso-core
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: main
          image: ghcr.io/nelcaso/core:0.1.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi