apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-pull-secret.sops.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - route.yaml
  - dapr-configuration.yaml
