apiVersion: v1
kind: Service
metadata:
  name: nelcaso-core
  namespace: nelcaso
  labels:
    app.kubernetes.io/name: nelcaso-core
    app.kubernetes.io/instance: nelcaso-core
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3500
      targetPort: dapr-http
      protocol: TCP
  selector:
    app.kubernetes.io/name: nelcaso-core
    app.kubernetes.io/instance: nelcaso-core